name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "6 6 6 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/dnscryptproxy-alpine:latest
    - name: Logout from Docker Hub
      run: docker logout
